[versions]
kotlin = "2.0.21"

dokka = "2.0.0-Beta"

[libraries]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version = "1.3.0"}